### ISSUE TITLE
Backstage Helm Charts - AWS RDS Support

### ISSUE THREAD

**Issue by regicsolutions** [RoadieHQ/helm-charts#25]
Is there any documentation on using an RDS PostgreSQL database vs using the baked in bitnami PostgreSQL image? i see the flag in values.yml but wasn't sure how the rest of the PostgreSQL configuration and keys were handled. My assumption is if rds is enabled PostgreSQL flags should be disabled?

I am looking to create 2 pods a frontend and backend that connects out to a PostgreSQL db in AWS RDS.

**Comment by martina-if** [comment]
Hi @regicsolutions , thanks for bringing this up. I will try to add some documentation for this. Let me also explain below how to do that. Please note that these charts are used by Roadie internally and are not necessarily useful for other use cases. You can find the general Backstage charts [here](https://github.com/backstage/backstage/tree/master/contrib/chart/backstage) and the documentation [here](https://backstage.io/docs/getting-started/deployment-helm).

1. The `rds.enabled` is only used to add the AWS [RDS CA](https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem) to a config map that can be mounted into backstage-backend and lighthouse.

2. When `postgresql.enabled=true` this chart will also deploy a bitnami postgresql instance and make sure that the backstage backend and lighthouse are connected to it. In your case, I would leave this disabled.

3. To configure access to your RDS instance you can follow [these instructions](https://github.com/backstage/backstage/tree/master/contrib/chart/backstage#custom-postgresql-instance). 

```
kubectl create configmap my-company-backstage-postgres-ca --from-file=ca.crt
```

```
postgresql:
  enabled: false

appConfig:
  app:
    baseUrl: https://backstage-demo.mydomain.com
    title: Backstage
  backend:
    baseUrl: https://backstage-demo.mydomain.com
    cors:
      origin: https://backstage-demo.mydomain.com
    database:
      client: pg
      connection:
        database: backstage_plugin_catalog
        host: <host>
        user: <pg user>
        password: <password>
  lighthouse:
    baseUrl: https://backstage-demo.mydomain.com/lighthouse-api

lighthouse:
  database:
    client: pg
    connection:
      host: <host>
      user: <pg user>
      password: <password>
      database: lighthouse_audit_service
```
